name: Unit test 
run-name: Running unit test with github action
on: [push]
jobs:
  Unit-Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Setup NodeJs
        uses: action/setup-node@v6
        with:24
      - name: Installing Depedencies
        run: pnpm install
      - name: running unit test
        run: pnpm test