name: Unit test 
run-name: Running unit test with github action
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with: 
          node-version: '22'
      - name: Installing Depedencies
        run: pnpm install
      - name: running unit test
        run: pnpm test